name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ghcr.io/${{ github.repository }} # org/repo format
  DOCKERFILE: ./Dockerfile
  CONTEXT: .

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.CONTEXT }}
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
      - name: Set full image reference with digest
        id: set-image-ref
        run: |
          DIGEST=${{ steps.build-image.outputs.digest }}

          IMAGE_REF="${{ env.IMAGE_NAME }}@${DIGEST}"

          # allows access in downstream job
          echo "image_ref=$IMAGE_REF" >> $GITHUB_OUTPUT

  terraform:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: 'write'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'personal-website-464720'
          workload_identity_provider: 'projects/905369188196/locations/global/workloadIdentityPools/github/providers/website'

      - uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=deploy init

      - name: Terraform Apply
        run: terraform -chdir=deploy apply -auto-approve -var="image_ref=${{ needs.build-and-push.outputs.image_ref }}" -var="project_id=personal-website-464720"
